Repository SesacDTeam/swim-done, pull requests merged in 2025-03, with the labels that each got.

#1 [SW-4] chore: 프론트엔드 환경 세팅
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/vite.config.js
Labels: chore

#2 [SW-8] chore: husky 설정
  .gitmessage
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  package-lock.json
  package.json
Labels: chore

#3 [SW-6] chore: intelli j 기본 폴더구조 및 의존성
  backend/.env.example
  backend/.gitattributes
  backend/.gitignore
  backend/build.gradle
  backend/compose.yaml
  backend/gradle.properties
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/done/swim/SwimApplication.java
  backend/src/main/java/com/done/swim/common/ApiResponse.java
  backend/src/main/java/com/done/swim/common/BaseTimeEntity.java
  backend/src/main/java/com/done/swim/config/JpaConfig.java
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/pool/Pool.java
  backend/src/main/java/com/done/swim/domain/pool/controller/PoolController.java
  backend/src/main/java/com/done/swim/domain/pool/dto/requestDto/CreatePoolRequestDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responseDto/CreatePoolResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/repository/PoolRepository.java
  backend/src/main/java/com/done/swim/domain/pool/service/PoolService.java
  backend/src/main/java/com/done/swim/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/done/swim/global/security/handler/CustomAccessDeniedHandler.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/done/swim/SwimApplicationTests.java
Labels: chore

#5 Chore/sw 13 fe css 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/axios.js
  frontend/src/components/common/수영장디테일.jsx
  frontend/src/components/markpools/MarkPools.jsx
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/poollist/PoolList.jsx
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Login.jsx
  frontend/src/router/index.jsx
  frontend/vite.config.js
Labels: chore

#6 [SW-14] chore: gzip 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/vite.config.js
Labels: chore

#7 [SW-15] docs: PR 템플릿 생성
  .github/pull_request_template.md
Labels: docs

#8 [SW-21] fix: SwimmingTimeRepository 에러 수정
  backend/src/main/java/com/done/swim/domain/swimmingtime/repository/SwimmingTimeRepository.java
Labels: fix

#13 [SW-27] 공통 css 이미지 세팅
  .husky/commit-msg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/contactUs.svg
  frontend/src/assets/home.svg
  frontend/src/assets/keywordReview.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/mark.svg
  frontend/src/assets/markPool.svg
  frontend/src/assets/more.svg
  frontend/src/assets/myReview.svg
  frontend/src/assets/mypage.svg
  frontend/src/assets/noContent.svg
  frontend/src/assets/pictureColor.svg
  frontend/src/assets/profile.svg
  frontend/src/assets/react.svg
  frontend/src/assets/swimming.svg
  frontend/src/assets/wave.svg
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/utils/staticImagePath.js
Labels: design, feat

#14 [SW-20] design: 사이드바 UI 구현
  frontend/src/App.jsx
  frontend/src/assets/contactUsColor.svg
  frontend/src/assets/keywordReviewColor.svg
  frontend/src/assets/markColor.svg
  frontend/src/assets/markPool.svg
  frontend/src/assets/markPoolColor.svg
  frontend/src/assets/myReviewColor.svg
  frontend/src/assets/mypage.svg
  frontend/src/assets/mypageColor.svg
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/components/sidebar/SideBarItem.jsx
  frontend/src/index.css
  frontend/src/pages/Home.jsx
  frontend/src/utils/staticImagePath.js
Labels: design

#15 [SW-31] feat: 네이버 소셜로그인 백엔드 구현
  backend/.env.example
  backend/build.gradle
  backend/src/main/java/com/done/swim/domain/user/entity/User.java
  backend/src/main/java/com/done/swim/domain/user/repository/UserRepository.java
  backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2User.java
  backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2UserService.java
  backend/src/main/java/com/done/swim/sociallogin/provider/NaverUserInfo.java
  backend/src/main/java/com/done/swim/sociallogin/provider/OAuth2UserInfo.java
  backend/src/main/resources/application.properties
Labels: feat

#12 [SW-23] feat: 수영장 상세조회 API 구현
  backend/src/main/java/com/done/swim/SwimApplication.java
  backend/src/main/java/com/done/swim/domain/pool/controller/PoolController.java
  backend/src/main/java/com/done/swim/domain/pool/dto/requestDto/CreatePoolRequestDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/requestdto/CreatePoolRequestDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responseDto/CreatePoolResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/CreatePoolResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/PoolDetailResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/entity/Pool.java
  backend/src/main/java/com/done/swim/domain/pool/repository/PoolRepository.java
  backend/src/main/java/com/done/swim/domain/pool/service/PoolService.java
  backend/src/main/java/com/done/swim/domain/poolreview/dto/responsedto/PoolDetailPageReviewResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolreview/entity/PoolReview.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/controller/SwimmingTimeController.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/dto/responsedto/FreeSwimmingTimeResponseDto.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/entity/SwimmingTime.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/entity/Week.java
Labels: feat

#17 [SW-33] feat: 네이버 소셜로그인 프론트엔드 토큰 로직 구현
  frontend/.env.example
  frontend/src/components/sociallogin/NaverLoginButton.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/NaverRedirect.jsx
  frontend/src/router/index.jsx
  frontend/src/store/slices/authSlice.js
  frontend/src/store/store.js
Labels: design, feat

#19 [SW-40] feat: 리뷰 생성 API 구현
  backend/src/main/java/com/done/swim/common/ApiResponse.java
  backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
  backend/src/main/java/com/done/swim/domain/poolreview/dto/requestdto/CreatePoolReviewRequestDto.java
  backend/src/main/java/com/done/swim/domain/poolreview/dto/responsedto/CreatePoolReviewResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java
Labels: refactor, feat

#21 [SW-36] 찜목록 조회 api 구현
  backend/src/main/java/com/done/swim/domain/poolmark/controller/PoolMarkController.java
  backend/src/main/java/com/done/swim/domain/poolmark/dto/PoolMarkListResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolmark/dto/PoolMarkResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolmark/entity/PoolMark.java
  backend/src/main/java/com/done/swim/domain/poolmark/repository/PoolMarkRepository.java
  backend/src/main/java/com/done/swim/domain/poolmark/service/PoolMarkService.java
  backend/src/main/resources/application.properties
Labels: feat

#22 [SW-42] static ImagePath named export로 변경
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/index.css
  frontend/src/utils/staticImagePath.js
Labels: chore

#25 [SW-42] feat: 찜목록 삭제 api 구현
  backend/src/main/java/com/done/swim/domain/poolmark/controller/PoolMarkController.java
  backend/src/main/java/com/done/swim/domain/poolmark/dto/PoolMarkResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolmark/repository/PoolMarkRepository.java
  backend/src/main/java/com/done/swim/domain/poolmark/service/PoolMarkService.java
Labels: feat

#24 [SW-41] refactor: 나의 리뷰 조회 API 구현
  backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
  backend/src/main/java/com/done/swim/domain/poolreview/dto/responsedto/MyReviewResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolreview/repository/PoolReviewRepository.java
  backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java
  backend/src/main/resources/application.properties
Labels: refactor, feat

#23 [SW-30] feat: 카카오톡 소셜로그인 백엔드 구현
  backend/build.gradle
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/user/entity/User.java
  backend/src/main/java/com/done/swim/domain/user/repository/UserRepository.java
  backend/src/main/java/com/done/swim/global/security/handler/OAuth2LoginFailureHandler.java
  backend/src/main/java/com/done/swim/global/security/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2User.java
  backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2UserService.java
  backend/src/main/java/com/done/swim/sociallogin/provider/KakaoUserInfo.java
  backend/src/main/java/com/done/swim/sociallogin/provider/NaverUserInfo.java
  backend/src/main/resources/application.properties
Labels: feat

#26 [SW-47] feat: 리뷰 수정 API 구현
  backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
  backend/src/main/java/com/done/swim/domain/poolreview/dto/requestdto/UpdatePoolReviewRequestDto.java
  backend/src/main/java/com/done/swim/domain/poolreview/dto/responsedto/UpdatePoolReviewResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolreview/entity/PoolReview.java
  backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java
Labels: feat

#27 [SW-39] feat: 네이버 소셜로그인 백엔드 로직 기능 구현 추가
  backend/.env.example
  backend/build.gradle
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/user/entity/User.java
  backend/src/main/java/com/done/swim/global/jwt/CustomUserDetailsService.java
  backend/src/main/java/com/done/swim/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/done/swim/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/done/swim/global/security/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/done/swim/global/security/handler/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2User.java
  backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2UserService.java
  backend/src/main/java/com/done/swim/sociallogin/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/done/swim/sociallogin/OAuth2TokenService.java
  backend/src/main/java/com/done/swim/sociallogin/TokenController.java
  backend/src/main/java/com/done/swim/sociallogin/provider/KakaoUserInfo.java
  backend/src/main/java/com/done/swim/sociallogin/provider/NaverUserInfo.java
  backend/src/main/java/com/done/swim/sociallogin/provider/OAuth2UserInfo.java
  backend/src/main/java/com/done/swim/sociallogin/provider/Provider.java
  backend/src/main/resources/application.properties
Labels: feat

#31 [SW-46] feat: 지도구현 Ver2
  .github/pull_request_template.md
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/pool/controller/SectionController.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/PoolDetailResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/PoolResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/SwimmingTimeSubDtoOfPoolResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/entity/Pool.java
  backend/src/main/java/com/done/swim/domain/pool/repository/PoolRepository.java
  backend/src/main/java/com/done/swim/domain/pool/service/PoolService.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/dto/responsedto/FreeSwimmingTimeResponseDto.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/dto/responsedto/SwimmingTimeResponseDto.java
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/components/kakaomap/KakaoMapService.js
  frontend/src/components/kakaomap/points.js
  frontend/src/components/sidebar/SideBar.jsx
Labels: feat

#32 [SW-48] 리스트바 나의 찜목록 UI 구현
  backend/src/main/java/com/done/swim/domain/poolmark/controller/PoolMarkController.java
  backend/src/main/java/com/done/swim/domain/poolmark/service/PoolMarkService.java
  frontend/src/api/markPoolApi.js
  frontend/src/components/common/NoContent.jsx
  frontend/src/components/common/PoolListItem.jsx
  frontend/src/components/markpools/MarkPools.jsx
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/hooks/useInfiniteScroll.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/store/slices/authSlice.js
  frontend/src/store/slices/sideBarSlice.js
  frontend/src/store/store.js
  frontend/src/utils/toggleMark.js
Labels: feat

#36 [SW-54] 액세스 토큰 재발급 로직 기능 구현
  backend/.env.example
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/done/swim/oauth2/CustomOAuth2User.java
  backend/src/main/java/com/done/swim/oauth2/OAuth2TokenService.java
  backend/src/main/java/com/done/swim/oauth2/TokenController.java
  backend/src/main/java/com/done/swim/oauth2/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/resources/application.properties
  frontend/src/api/authApi.js
  frontend/src/api/axios.js
  frontend/src/pages/LoginRedirect.jsx
  frontend/src/router/index.jsx
  frontend/src/store/slices/authSlice.js
Labels: fix, refactor, feat

#34 [SW-58] 수영장 상세조회 페이지 구현
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/PoolDetailResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/PoolDetailReviewResponseDto.java
  backend/src/main/java/com/done/swim/domain/poolreview/dto/responsedto/PoolDetailPageReviewResponseDto.java
  frontend/src/api/poolApi.js
  frontend/src/assets/back.svg
  frontend/src/assets/xmark.svg
  frontend/src/components/common/DetailViewHeader.jsx
  frontend/src/components/common/PoolListItem.jsx
  frontend/src/components/common/createreview/CreateReview.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/common/pooldetail/ReviewListItem.jsx
  frontend/src/components/common/submitImage/SubmitImage.jsx
  frontend/src/components/common/수영장디테일.jsx
  frontend/src/components/markpools/MarkPools.jsx
  frontend/src/hooks/useUnmount.jsx
  frontend/src/router/index.jsx
  frontend/src/store/slices/detailViewSlice.js
  frontend/src/store/store.js
  frontend/src/utils/extractDate.js
  frontend/src/utils/staticImagePath.js
Labels: feat

#35 Feat/sw 61 마이페이지 리스트바 구현
  .idea/vcs.xml
  backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
  backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/mypage/MyPageItem.jsx
  frontend/src/store/slices/userSlice.js
  frontend/src/store/store.js
  frontend/src/utils/staticImagePath.js
Labels: feat

#38 [SW-64] 라우터 에러페이지 구현
  frontend/src/pages/NotFound.jsx
  frontend/src/router/index.jsx
Labels: feat

#39 [SW-59] 리뷰 작성 페이지 구현
  frontend/src/api/authApi.js
  frontend/src/api/axios.js
  frontend/src/api/reviewApi.js
  frontend/src/components/common/createreview/CreateReview.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
Labels: feat

#41 [SW-65] 백엔드 전역 예외처리 구현
  backend/src/main/java/com/done/swim/domain/pool/service/PoolService.java
  backend/src/main/java/com/done/swim/domain/poolmark/service/PoolMarkService.java
  backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
  backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java
  backend/src/main/java/com/done/swim/global/exception/ErrorCode.java
  backend/src/main/java/com/done/swim/global/exception/ForBiddenException.java
  backend/src/main/java/com/done/swim/global/exception/GlobalException.java
  backend/src/main/java/com/done/swim/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/done/swim/global/exception/InvalidRefreshTokenException.java
  backend/src/main/java/com/done/swim/global/exception/ResourceNotFoundException.java
  backend/src/main/java/com/done/swim/global/exception/ServerErrorException.java
  backend/src/main/java/com/done/swim/global/exception/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/done/swim/global/security/handler/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/done/swim/oauth2/OAuth2TokenService.java
  backend/src/main/java/com/done/swim/oauth2/TokenController.java
Labels: feat

#42 [SW-67] 이미지 업로드 API 구현 및 S3 계정 세팅
  backend/build.gradle
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
  backend/src/main/java/com/done/swim/domain/submittedimage/controller/SubmittedImageController.java
  backend/src/main/java/com/done/swim/domain/submittedimage/dto/requestdto/SubmittedImageRequestDto.java
  backend/src/main/java/com/done/swim/domain/submittedimage/dto/responsedto/SubmittedImageResponseDto.java
  backend/src/main/java/com/done/swim/domain/submittedimage/entity/SubmittedImage.java
  backend/src/main/java/com/done/swim/domain/submittedimage/service/SubmittedImageService.java
  backend/src/main/java/com/done/swim/global/awss3/AwsS3Config.java
  backend/src/main/java/com/done/swim/global/awss3/AwsS3Service.java
Labels: feat

#43 [SW-56] feat: 카카오톡 소셜로그인 로그아웃 구현
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/user/entity/User.java
  backend/src/main/java/com/done/swim/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/done/swim/oauth2/CustomOAuth2User.java
  backend/src/main/java/com/done/swim/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/done/swim/oauth2/OAuth2TokenService.java
  backend/src/main/java/com/done/swim/oauth2/handler/OAuth2LoginFailureHandler.java
  backend/src/main/java/com/done/swim/oauth2/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/resources/application.properties
  frontend/src/api/axios.js
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/components/sociallogin/KakaoLoginButton.jsx
  frontend/src/pages/LoginRedirect.jsx
Labels: feat

#33 [SW-9} chore: dp aws
  .github/workflows/deploy.yml
  backend/Dockerfile
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/oauth2/OAuth2TokenService.java
  docker-compose-actions.yml
  docker-compose.yml
  frontend/Dockerfile
  frontend/conf.d/default.conf
  frontend/nginx.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/axios.js
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/components/kakaomap/KakaoMapService.js
  frontend/src/components/sociallogin/KakaoLoginButton.jsx
  frontend/src/components/sociallogin/NaverLoginButton.jsx
  frontend/src/router/index.jsx
  frontend/src/store/slices/kakaoMapSlice.js
  frontend/templates/default.conf.template
  frontend/templates/https.conf.template
Labels: chore

#46 [SW-69] 인증이 필요한 페이지 예외처리
  frontend/src/components/common/AuthenticateRoute.jsx
  frontend/src/components/common/DetailViewHeader.jsx
  frontend/src/components/common/UnauthenticateRoute.jsx
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/components/markpools/MarkPools.jsx
  frontend/src/components/poollist/PoolList.jsx
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/LoginRedirect.jsx
  frontend/src/router/index.jsx
  frontend/src/store/slices/kakaoMapSlice.js
  frontend/src/store/slices/listBarSlice.js
  frontend/src/store/slices/sideBarSlice.js
  frontend/src/store/store.js
  frontend/vite.config.js
Labels: feat

#47 [SW-71] 이미지 제보 페이지 구현
  backend/src/main/java/com/done/swim/domain/submittedimage/controller/SubmittedImageController.java
  backend/src/main/java/com/done/swim/domain/submittedimage/service/SubmittedImageService.java
  backend/src/main/java/com/done/swim/global/exception/ErrorCode.java
  backend/src/main/resources/application.properties
  frontend/src/api/submittedImageApi.js
  frontend/src/assets/defaultUploadImage.svg
  frontend/src/components/common/createreview/CreateReview.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/common/submitImage/SubmitImage.jsx
  frontend/src/components/common/submittedImage/SubmittedImage.jsx
  frontend/src/router/index.jsx
  frontend/src/utils/staticImagePath.js
Labels: refactor, feat

#48 [SW-44] feat: 인포윈도우
  backend/src/main/java/com/done/swim/config/SecurityConfig.java
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/PoolWithSwimmingTimeResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/repository/PoolRepository.java
  backend/src/main/java/com/done/swim/domain/pool/service/PoolService.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/controller/SwimmingTimeController.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/dto/requestdto/SwimmingTimeRequestDto.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/dto/responsedto/SwimmingTimeResponseDto.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/entity/SwimmingTime.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/entity/Week.java
  backend/src/main/java/com/done/swim/domain/swimmingtime/service/SwimmingTimeService.java
  backend/src/main/resources/application.properties
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/components/poollist/InfoWindowContent.jsx
  frontend/src/components/poollist/InfoWindowContentPortal.jsx
Labels: fix, design, feat

#49 [SW-74] design: 로그인 페이지 디자인 변경
  frontend/src/assets/logo2.svg
  frontend/src/assets/logoMan.svg
  frontend/src/components/sociallogin/KakaoLoginButton.jsx
  frontend/src/components/sociallogin/NaverLoginButton.jsx
  frontend/src/pages/Login.jsx
  frontend/src/utils/staticImagePath.js
Labels: design

#52 [SW-77] 깃허브 소셜로그인 기능 구현
  backend/src/main/java/com/done/swim/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/done/swim/oauth2/provider/GithubUserInfo.java
  backend/src/main/java/com/done/swim/oauth2/provider/Provider.java
  backend/src/main/resources/application.properties
  frontend/src/components/sociallogin/GithubLoginButton.jsx
  frontend/src/pages/Login.jsx
Labels: feat

#53 [SW-73] 전역 에러처리
  backend/src/main/java/com/done/swim/global/exception/ErrorCode.java
  backend/src/main/java/com/done/swim/global/exception/handler/GlobalExceptionHandler.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/axios.js
  frontend/src/api/kakaoMapApi.js
  frontend/src/api/markPoolApi.js
  frontend/src/api/setupRequestInterceptor.js
  frontend/src/api/setupResponseInterceptor.js
  frontend/src/components/common/createreview/CreateReview.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/common/submittedImage/SubmittedImage.jsx
  frontend/src/components/markpools/MarkPools.jsx
  frontend/src/error/ERROR_CODE.js
  frontend/src/error/ERROR_DISPLAY_MODE.js
  frontend/src/error/ErrorBoundary.jsx
  frontend/src/error/ErrorCatcher.jsx
  frontend/src/error/RequestError.js
  frontend/src/hooks/useErrorResolver.jsx
  frontend/src/hooks/useToggleMark.jsx
  frontend/src/index.css
  frontend/src/pages/Home.jsx
  frontend/src/router/index.jsx
  frontend/src/store/slices/errorSlice.js
  frontend/src/store/store.js
Labels: feat

#54 [SW- 78]chore: 소셜로그인 관련 nginx
  backend/src/main/java/com/done/swim/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/done/swim/oauth2/provider/Provider.java
  frontend/src/components/sociallogin/GithubLoginButton.jsx
  frontend/src/components/sociallogin/KakaoLoginButton.jsx
  frontend/src/components/sociallogin/NaverLoginButton.jsx
  frontend/templates/https.conf.template
Labels: chore

#61 [SW-88] 리뷰 작성 이미지 제보 페이지 예외 처리
  backend/src/main/java/com/done/swim/domain/submittedimage/service/SubmittedImageService.java
  frontend/src/components/common/createreview/CreateReview.jsx
  frontend/src/components/common/submittedImage/SubmittedImage.jsx
  frontend/src/hooks/useErrorResolver.jsx
Labels: design, refactor, feat

#63 [SW-92] error boundary fallback UI 디자인 수정
  frontend/src/error/ErrorBoundary.jsx
Labels: design

#65 [SW-90] 프론트엔드 코드 정리
  frontend/src/api/authApi.js
  frontend/src/api/kakaoMapApi.js
  frontend/src/api/reviewApi.js
  frontend/src/api/setupRequestInterceptor.js
  frontend/src/assets/logoMan.svg
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/common/updatereview/UpdateReview.jsx
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/mypage/MyReviewPage.jsx
  frontend/src/components/mypage/MyReviewPageItem.jsx
  frontend/src/components/poollist/PoolList.jsx
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/components/sidebar/SideBarItem.jsx
  frontend/src/components/sociallogin/GithubLoginButton.jsx
  frontend/src/components/sociallogin/KakaoLoginButton.jsx
  frontend/src/components/sociallogin/NaverLoginButton.jsx
  frontend/src/index.css
  frontend/src/pages/Login.jsx
  frontend/src/pages/LoginRedirect.jsx
  frontend/src/router/index.jsx
  frontend/src/utils/staticImagePath.js
  frontend/src/utils/toggleMark.js
Labels: fix, refactor

#66 [SW-86] 내가 남긴 리뷰 페이지 뒤로가기 버튼 구현
  backend/src/main/java/com/done/swim/domain/poolmark/entity/PoolMark.java
  backend/src/main/java/com/done/swim/domain/poolreview/entity/PoolReview.java
  backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java
  backend/src/main/java/com/done/swim/domain/user/entity/User.java
Labels: fix, design, feat

#67 [SW-95] PoolReviewService 에러 수정
  backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java
Labels: fix

#68 [SW-94] 최근 로그인 기능 구현
  backend/src/main/java/com/done/swim/oauth2/handler/OAuth2LoginSuccessHandler.java
  frontend/src/components/sociallogin/GithubLoginButton.jsx
  frontend/src/components/sociallogin/KakaoLoginButton.jsx
  frontend/src/components/sociallogin/NaverLoginButton.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/LoginRedirect.jsx
  frontend/src/store/slices/authSlice.js
Labels: feat

#69 [SW-96] 리뷰 수정 생성 페이지 로직 수정
  frontend/src/components/common/DetailViewHeader.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/mypage/MyPageItem.jsx
  frontend/src/components/mypage/MyReviewPage.jsx
  frontend/src/components/mypage/MyReviewPageItem.jsx
  frontend/src/router/index.jsx
Labels: fix

#71 [SW-102] fix: 지도 버그 수정
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/store/slices/kakaoMapSlice.js
Labels: fix

#73 [SW-99] alert 디자인 및 toast alert 로직 적용
  frontend/src/components/common/AlertModal.jsx
  frontend/src/components/common/AuthenticateRoute.jsx
  frontend/src/components/common/createreview/CreateReview.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/common/submittedImage/SubmittedImage.jsx
  frontend/src/components/common/updatereview/UpdateReview.jsx
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/mypage/MyReviewPageItem.jsx
  frontend/src/pages/Login.jsx
Labels: refactor, feat

#74 [SW-103] feat: 지도 에러 토스트
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/error/ERROR_CODE.js
  frontend/src/hooks/useErrorResolver.jsx
  frontend/src/router/index.jsx
Labels: design, feat
