Repository SesacDTeam/swim-done, pull requests merged in 2025-04, with the labels that each got.

#79 [SW-104] 마커 오류 토스트 추가
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/error/ErrorBoundary.jsx
  frontend/src/hooks/useErrorResolver.jsx
Labels: chore, feat

#82 [SW-109] 리뷰 작성 수정 페이지 에러 수정
  frontend/src/components/common/review/CreateReview.jsx
  frontend/src/components/common/review/UpdateReview.jsx
  frontend/src/error/ErrorCatcher.jsx
  frontend/src/hooks/useErrorResolver.jsx
  frontend/src/hooks/useSubmitReview.jsx
Labels: fix

#80 [SW-107] 최근 로그인 이력 카카오 네이버 구분
  backend/src/main/java/com/done/swim/domain/submittedimage/dto/responsedto/SubmittedImageResponseDto.java
  backend/src/main/java/com/done/swim/domain/user/entity/User.java
  backend/src/main/java/com/done/swim/oauth2/provider/GithubUserInfo.java
  backend/src/main/java/com/done/swim/oauth2/service/CustomOAuth2UserService.java
Labels: fix, feat

#84 [SW-112] feat: 리뷰 작성 후 엔터 클릭시 리뷰 중복 생성 막음
  frontend/src/components/common/AlertModal.jsx
Labels: feat

#85 [SW-114] 배포 에러 수정
  frontend/src/components/common/LoadingSpinner.jsx
Labels: fix, chore

#88 [SW-115] error boundary 재시도 구현
  frontend/src/components/markpools/MarkPools.jsx
  frontend/src/error/ErrorBoundary.jsx
  frontend/src/hooks/useErrorResolver.jsx
Labels: feat

#89 [SW-116] refactor: 최근 로그인 이력 컴포넌트로 분리
  frontend/src/components/sociallogin/GithubLoginButton.jsx
  frontend/src/components/sociallogin/KakaoLoginButton.jsx
  frontend/src/components/sociallogin/NaverLoginButton.jsx
  frontend/src/components/sociallogin/RecentLoginLabel.jsx
  frontend/src/pages/Login.jsx
Labels: refactor

#95 [SW-124] 리프레시 토큰 저장 로직 재수정
  backend/src/main/java/com/done/swim/oauth2/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/done/swim/oauth2/service/OAuth2TokenService.java
Labels: chore

#96 [SW-122] 로고 및 파비콘 적용
  frontend/index.html
  frontend/public/favicon.svg
  frontend/public/vite.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/logo2.svg
  frontend/src/assets/poolBuoy.svg
  frontend/src/components/common/loadingSpinner.jsx
  frontend/src/components/sidebar/SideBar.jsx
  frontend/src/utils/staticImagePath.js
Labels: design

#93 [SW-120] fix: 마커 변경
  frontend/src/assets/mapMarker.png
  frontend/src/components/kakaomap/KakaoMapContainer.jsx
  frontend/src/utils/staticImagePath.js
Labels: design

#99 [SW-125] design: 로딩중 이미지 풀부이 변경
  frontend/src/components/common/LoadingSpinner.jsx
Labels: design

#100 [SW-126] 충동 해결용
  frontend/src/components/common/loadingSpinner.jsx
Labels: fix

#103 [SW-129] 링크 공유 미리보기 화면 세팅 및 백엔드 에러 응답코드 수정
  backend/src/main/java/com/done/swim/global/exception/handler/GlobalExceptionHandler.java
  frontend/index.html
  frontend/public/logo.png
Labels: fix, design

#104 [SW-131] 이미지 제출 후 navigate 경로 수정
  frontend/src/components/common/submittedImage/SubmittedImage.jsx
Labels: fix

#105 [SW-132] 링크 미리보기 수정
  frontend/index.html
  frontend/public/logo.png
  frontend/public/logo_1200x630.png
  frontend/public/logo_800x400.png
Labels: fix, design

#106 [SW-133] 리뷰작성 제보하기 로딩 구현
  frontend/src/components/common/AlertModal.jsx
  frontend/src/components/common/LoadingSpinner.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/common/review/CreateReview.jsx
  frontend/src/components/common/review/UpdateReview.jsx
  frontend/src/components/common/submittedImage/SubmittedImage.jsx
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/mypage/MyReviewPage.jsx
  frontend/src/components/mypage/MyReviewPageItem.jsx
Labels: feat

#107 [SW-135] 제보하기 로딩처리 에러 수정
  frontend/src/components/common/submittedImage/SubmittedImage.jsx
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/sidebar/SideBar.jsx
Labels: fix

#108 [SW-134] 메인 페이지 알림 추가
  frontend/src/components/common/AlertModal.jsx
  frontend/src/components/common/MainBanner.jsx
  frontend/src/components/common/pooldetail/PoolDetail.jsx
  frontend/src/components/common/pooldetail/TimeTable.jsx
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/index.css
  frontend/src/pages/Home.jsx
Labels: design, feat

#111 [SW-136] getPollWitName api 쿼리 수정
  backend/src/main/java/com/done/swim/domain/pool/dto/responsedto/PoolWithSwimmingTimeResponseDto.java
  backend/src/main/java/com/done/swim/domain/pool/repository/PoolRepository.java
Labels: fix

#112 Update README.md
  README.md
Labels: docs

#113 [SW-137]docs: update readme.md
  README.md
  readme/cicd.png
Labels: docs

#114 [SW-138] 시연영상 추가
  README.md
Labels: docs
